### ISSUE TITLE
Cannot access to "WYWEB on CADAL"

### ISSUE THREAD

**Issue by KoichiYasuoka** [baudzhou/WYWEB#1]
> See [WYWEB on CADAL](https://github.com/baudzhou/WYWEB/blob/master/www.cadal.zju.edu.cn/wyweb) for the official leader-board.

Sorry @baudzhou but I cannot see "WYWEB on CADAL". Please link to appropriate URL.

**Comment by baudzhou** [comment]
Sorry for late reply, the link has been fixed.
See [www.dcd.zju.edu.cn/wyweb](http://www.dcd.zju.edu.cn/wyweb)

**Comment by WiiliamC** [comment]
[www.dcd.zju.edu.cn/wyweb](http://www.dcd.zju.edu.cn/wyweb)依然打不开
